services:
  ros2-srv-humble:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
        USERNAME: user1000
        USER_UID: 1000
        USER_GID: 1000
    container_name: ros2-cont-humble
    volumes:
      - ../src:/home/${USERNAME}/ros2_ws/src:rw
      - ../../shared:/home/${USERNAME}/shared:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DISTRO=humble
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    devices:
      - /dev/dri:/dev/dri
